# Generated by Django 4.0.3 on 2022-06-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsale',
            old_name='quantity',
            new_name='pieces',
        ),
    ]
