# Generated by Django 4.0.3 on 2022-07-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
