# Generated by Django 4.0.3 on 2022-04-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(null=True, to='api.product'),
        ),
    ]
