# Generated by Django 4.0.3 on 2022-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sale_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
