# Generated by Django 4.0.3 on 2022-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Pending', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Pending', max_length=256),
            preserve_default=False,
        ),
    ]
